services:
  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET}
    container_name: sveltekit_app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - db

  db:
    container_name: pg_db
    build:
      context: .
      dockerfile: ./dockerfiles/db/Dockerfile
    volumes:
      - ./dockerfiles/db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "5432:5432"
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - shared_preload_libraries=pg_stat_statements
    healthcheck:
      test: ["CMD-SHELL", "PGUSER=postgres", "pg_isready"]
      interval: 1s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sb

volumes:
  st_data:
